[package]
name = "sr_client"
version = "0.0.1"
authors = ["apelimsky <a@0x41.co>"]
edition = "2018"

[[bin]]
name = "sr_client"
path = "src/main.rs"

[dependencies]
ncurses = "^5.99.0"
serde_json = "^1.0"
sr_lib = { path = "../lib", version = "^0.0.1" }
