[package]
name = "sr_client"
version = "0.0.1"
authors = ["apelimsky <a@0x41.co>"]
edition = "2018"

[[bin]]
name = "sr_client"
path = "src/main.rs"

[dependencies]
laminar = "0.4"
tui = "^0.13"
termion = "^1.5"
serde_json = "^1.0"
sr_lib = { path = "../lib", version = "^0.0.1" }
