[package]
name = "sr_server"
version = "0.0.1"
authors = ["apelimsky <a@0x41.co>"]
edition = "2018"

[[bin]]
name = "sr_server"
path = "src/main.rs"

[dependencies]
laminar = "0.4"
rusqlite = "^0.24.2"
sr_lib = { path = "../lib", version = "^0.0.1" }
